[package]
name = "backup"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
blake3 = "1.7.0"
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.34", features = ["derive"] }
colored = "3.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tempfile = "3.19.1"
